"""Tablas de códigos del Servicio Nacional de Aduanas usadas en documentos de
exportación (CodPaisRecep, CodPtoEmbarque, CodViaTransp, CodClauVenta, CodModVenta,
CodTpoBultos, unidades de medida, FmaPagExp).

GENERADO desde los seeds oficiales de pos-matic_no
(supabase/migrations/20260826140100_aduana_tablas_referencia.sql y
20260826140200_aduana_seed_paises_monedas_bultos_puertos.sql). Las unidades de
medida y formas de pago vienen de la tabla de Aduana usada en el DUS (misma que
LibreDTE); KN=6 coincide con SII_pudu_Server (UNIDAD_MEDIDA_ADUANA_KG='06').
Claves normalizadas: mayúsculas sin acentos.
"""
import re
import unicodedata


def norm(s: str) -> str:
    return unicodedata.normalize("NFKD", s or "").encode("ascii", "ignore").decode().upper().strip()


_PAREN = re.compile(r"\([^)]*\)")
_SEPARADORES = re.compile(r"[.\-_/,;]+")
_ESPACIOS = re.compile(r"\s+")


def clave(s: str) -> str:
    """Normalización tolerante para comparar: sin acentos, sin puntos ni guiones
    ("U.S.A." → "U S A") y sin sufijos entre paréntesis que solo existen en la
    tabla de Aduana ("REPUBLICA CHECA (D)" → "REPUBLICA CHECA")."""
    k = _PAREN.sub(" ", norm(s))
    k = _SEPARADORES.sub(" ", k)
    return _ESPACIOS.sub(" ", k).strip()


PAISES = {"AFGHANISTAN": 308, "ALBANIA": 518, "ALEMANIA": 563, "ANDORRA": 525, "ANGOLA": 140, "ANGUILA": 242, "ANTIGUA Y BARBUDA": 240, "ANTILLAS NEERLANDESAS": 247, "APROVISIONAMIENTO (\"RANCHO\") DE NAVES Y AERONAVES EXTRANJERAS Y DE MADERAS PARA ESTIBAR MERCANCIAS CARGADAS EN PUERTOS CHILENOS": 902, "ARABIA SAUDITA": 302, "ARGELIA": 127, "ARGENTINA": 224, "ARMENIA": 540, "ARUBA": 243, "AUSTRALIA": 406, "AUSTRIA": 509, "AZERBAIJAN": 541, "BAHAMAS": 207, "BAHREIN": 313, "BANGLADESH": 321, "BARBADOS": 204, "BELARUS": 542, "BELAU": 420, "BELGICA": 514, "BELICE": 236, "BENIN": 150, "BERMUDAS": 244, "BOLIVIA": 221, "BOSNIA Y HERZEGOVINA": 543, "BOTSWANA": 113, "BRASIL": 220, "BRUNEI": 344, "BULGARIA": 527, "BURKINA FASO": 161, "BURUNDI": 141, "BUTAN": 318, "CABO VERDE": 129, "CAMBODIA": 315, "CAMERUN": 149, "CANADA": 226, "CHAD": 130, "CHILE": 997, "CHINA": 336, "CHIPRE": 305, "COLOMBIA": 202, "COMBUSTIBLES Y LUBRICANTES DESTINADOS AL CONSUMO DE NAVES Y AERONAVES EXTRANJERAS Y DE REVISTAS CON EL MISMO OBJETO": 901, "COMORAS": 118, "CONGO": 144, "COREA DEL NORTE": 334, "COREA DEL SUR": 333, "COSTA DE MARFIL": 107, "COSTA RICA": 211, "CROACIA": 547, "CUBA": 209, "DEPOSITO FRANCO": 906, "DINAMARCA": 507, "DJIBOUTI": 155, "DOMINICA": 231, "ECUADOR": 218, "EGIPTO": 124, "EL SALVADOR": 213, "EMIRATOS ARABES UNIDOS": 341, "ERITREA": 163, "ESLOVENIA": 548, "ESPANA": 517, "ESTADOS UNIDOS DE AMERICA": 225, "ESTONIA": 549, "ETIOPIA": 139, "FIJI": 401, "FILIPINAS": 335, "FINLANDIA": 512, "FRANCIA": 505, "GABON": 145, "GAMBIA": 102, "GEORGIA": 550, "GHANA": 108, "GIBRALTAR": 565, "GRANADA": 232, "GRECIA": 520, "GROENLANDIA": 253, "GUAM": 425, "GUATEMALA": 215, "GUERNSEY": 566, "GUINEA": 104, "GUINEA - BISSAU": 103, "GUINEA ECUATORIAL": 147, "GUYANA": 217, "HAITI": 208, "HONDURAS": 214, "HONG KONG - REGION ADMINISTRATIVA ESPECIAL DE CHINA": 342, "HUNGRIA": 530, "INDIA": 317, "INDONESIA": 328, "IRAK": 307, "IRAN": 309, "IRLANDA": 506, "ISLANDIA": 516, "ISLAS CAYMAN": 246, "ISLAS COOK": 427, "ISLAS DE MAN": 567, "ISLAS MALDIVAS": 327, "ISLAS MARIANAS DEL NORTE": 424, "ISLAS MARSHALL": 164, "ISLAS SALOMON": 418, "ISLAS TONGA": 403, "ISLAS VIRGENES (ESTADOS UNIDOS DE AMERICA)": 249, "ISLAS VIRGENES BRITANICAS": 245, "ISRAEL": 306, "ITALIA": 504, "JAMAICA": 205, "JAPON": 331, "JERSEY": 568, "JORDANIA": 301, "KASAJSTAN": 551, "KENIA": 137, "KIRGISTAN": 552, "KIRIBATI": 416, "KUWAIT": 303, "LAOS": 316, "LESOTHO": 114, "LETONIA": 553, "LIBANO": 311, "LIBERIA": 106, "LIBIA": 125, "LIECHTENSTEIN": 534, "LITUANIA": 554, "LUXEMBURGO": 532, "MACAO": 345, "MACEDONIA": 555, "MADAGASCAR": 120, "MALASIA": 329, "MALAWI": 115, "MALI": 133, "MALTA": 523, "MARRUECOS": 128, "MARTINICA": 250, "MAURICIO": 119, "MAURITANIA": 134, "MEXICO": 216, "MICRONESIA": 417, "MOLDOVA": 556, "MONACO": 535, "MONGOLIA": 337, "MONSERRAT": 252, "MONTENEGRO": 561, "MOZAMBIQUE": 121, "MYANMAR (EX BIRMANIA)": 326, "NACIONAL REPUTADA": 998, "NAMIBIA": 159, "NAURU": 402, "NEPAL": 320, "NICARAGUA": 212, "NIGER": 131, "NIGERIA": 111, "NIUE": 421, "NORUEGA": 513, "NUEVA CALEDONIA": 423, "NUEVA ZELANDIA": 405, "OMAN": 304, "ORIGENES O DESTINACIONES NO PRECISADAS POR RAZONES COMERCIALES O MILITARES": 904, "OTROS (PAIS DESCONOCIDO)": 999, "PAISES BAJOS": 515, "PAKISTAN": 324, "PALESTINA": 322, "PANAMA": 210, "PAPUA, NUEVA GUINEA": 412, "PARAGUAY": 222, "PERU": 219, "PESCA EXTRATERRITORIAL": 903, "POLINESIA FRANCESA": 422, "POLONIA": 528, "PORTUGAL": 501, "PUERTO RICO": 251, "QATAR": 312, "REINO UNIDO": 510, "REPUBLICA CENTRO AFRICANA": 148, "REPUBLICA CHECA (D)": 544, "REPUBLICA DE SERBIA": 546, "REPUBLICA DE YEMEN": 346, "REPUBLICA DEMOCRATICA DEL CONGO": 143, "REPUBLICA DOMINICANA": 206, "REPUBLICA ESLOVACA (D)": 545, "RUMANIA": 519, "RUSIA (B)": 562, "RWANDA": 142, "SAHARA OCCIDENTAL": 165, "SAINT KITTS & NEVIS": 241, "SAMOA OCCIDENTAL": 404, "SAN MARINO": 536, "SAN VICENTE Y LAS GRANADINAS": 234, "SANTA LUCIA (ISLAS OCCIDENTALES)": 233, "SANTA SEDE": 524, "SAO TOME Y PRINCIPE": 146, "SENEGAL": 101, "SEYCHELLES": 156, "SIERRA LEONA": 105, "SINGAPUR": 332, "SIRIA": 310, "SOMALIA": 138, "SRI LANKA": 314, "SUDAFRICA": 112, "SUDAN": 123, "SUDAN DEL SUR": 160, "SUECIA": 511, "SUIZA": 508, "SURINAM": 235, "SWAZILANDIA": 122, "TADJIKISTAN": 557, "TAIWAN (FORMOSA)": 330, "TANZANIA": 135, "TERRITORIO BRITANICO EN AFRICA": 151, "TERRITORIO BRITANICO EN AMERICA": 227, "TERRITORIO BRITANICO EN OCEANIA Y EL PACIFICO": 407, "TERRITORIO DE DINAMARCA": 230, "TERRITORIO ESPANOL EN AFRICA": 152, "TERRITORIO FRANCES EN AFRICA": 153, "TERRITORIO FRANCES EN AMERICA": 228, "TERRITORIO FRANCES EN OCEANIA Y EL PACIFICO": 408, "TERRITORIO HOLANDES EN AMERICA": 229, "TERRITORIO NORTEAMERICANO EN OCEANIA Y EL PACIFICO": 409, "TERRITORIO PORTUGUES EN ASIA": 343, "THAILANDIA": 319, "TIMOR ORIENTAL": 426, "TOGO": 109, "TRINIDAD Y TOBAGO": 203, "TUNEZ": 126, "TURCAS Y CAICOS": 248, "TURKMENISTAN": 558, "TURQUIA": 522, "TUVALU": 419, "UCRANIA": 559, "UGANDA": 136, "URUGUAY": 223, "UZBEKISTAN": 560, "VANUATU": 415, "VENEZUELA": 201, "VIETNAM": 325, "ZAMBIA": 117, "ZIMBABWE": 116, "ZONA FRANCA ARICA, ZONA INDUSTRIAL": 910, "ZONA FRANCA IQUIQUE": 905, "ZONA FRANCA PUNTA ARENAS": 907}

PUERTOS = {"AALBORG": 644, "AARHUS": 641, "ABRA DE NAPA": 960, "ACAPULCO": 218, "ADELAIDA": 814, "AERODROMO EL LOA": 993, "AERODROMO LA ARAUCANIA": 825, "AERODROMO PICHOY": 831, "AEROP. A.M. BENITEZ": 992, "AEROP. C.I. DEL CAMPO": 991, "AEROP. CERRO MORENO": 989, "AEROP. CHACALLUTA": 987, "AEROP. DIEGO ARACENA": 988, "AEROP. EL TEPUAL": 990, "AEROPUERTO CARRIEL SUR": 945, "AGUAS NEGRAS": 951, "ALGECIRAS": 568, "ALTAMIRA": 220, "AMBERES": 601, "AMSTERDAM": 621, "ANCUD": 931, "ANTOFAGASTA": 903, "APPELEG": 974, "ARICA": 901, "ARICA-LA PAZ": 995, "ARICA-TACNA": 994, "AUGUSTA": 546, "BAHIA BLANCA": 266, "BAKER": 978, "BALBOA": 222, "BALTIMORE": 136, "BARCELONA": 563, "BARRANQUILLA": 233, "BATON ROUGE": 146, "BAYSIDE": 118, "BELGRADO": 533, "BILBAO": 564, "BOSTON": 131, "BREMEN": 591, "BREST": 557, "BRIDGEPORT": 133, "BROWNSVILLE": 158, "BUENAVENTURA": 232, "BUENOS AIRES": 262, "BURDEOS": 555, "BUSAN": 422, "CABO NEGRO": 942, "CADIZ": 562, "CALAIS": 556, "CALBUCO": 205, "CALCUTA": 471, "CALDERA": 918, "CALDERILLA": 919, "CALETA COLOSO": 950, "CALLAO": 252, "CARDENAL SAMORE": 967, "CASAS VIEJAS": 980, "CASTRO": 932, "CHACABUCO PUERTO AYSEN": 911, "CHACALLUTA": 957, "CHAITEN": 934, "CHALNA": 481, "CHANARAL BARQUITO": 917, "CHARLESTON": 139, "CHILE CHICO": 977, "CHUNGARA": 958, "CIUDAD DEL CABO": 712, "CLARENCIA": 940, "COATZACOALCOS": 214, "COLCHANE": 959, "COLON": 223, "COLUMBRES": 147, "COMBUSTIBLES Y LUBRICANTES DESTINADOS AL CONSUMO DE NAVES Y AERONAVES DE TRANSPORTE INTERNACIONAL": 900, "COMODORO RIVADAVIA": 267, "CONSTANZA": 511, "CONSTITUCION": 923, "COPENHAGEN": 642, "COQUIMBO": 904, "CORDOBA": 265, "CORONEL": 926, "CORPUS CRISTI": 157, "CORRAL": 930, "COSTA DEL ATLANTICO, OTROS NO ESPECIFICADOS COMPRENDIDOS ENTRE MAINE Y KEY WEST": 121, "COSTA DEL PACIFICO, OTROS NO ESPECIFICADOS": 123, "COSTA DEL PACIFICO, OTROS PUERTOS": 212, "COYHAIQUE ALTO": 983, "CRISTOBAL": 221, "CURAZAO": 302, "CUXHAVEN": 597, "DAIREN": 412, "DARWIN": 815, "DOROTEA": 979, "DOVER": 577, "DULUTH": 149, "DURBAM": 711, "DUSSELDORF": 595, "EAST-LONDON": 717, "ESTACION DE MEDICION RECINTO": 826, "ETEN SALVERRY": 574, "EVERGLADES": 142, "FILADELFIA": 135, "FRANKFURT": 594, "FREMANTLE": 812, "FUKUYAMA": 449, "FUTALEUFU": 969, "GALVESTON": 156, "GENOVA": 542, "GERALDTON": 816, "GHENT": 604, "GNL MEJILLONES": 999, "GOLFO DE MEXICO, OTROS NO ESPECIFICADOS": 219, "GOTEMBURGO": 631, "GREGORIO": 941, "GUARELLO": 937, "GUAYACAN": 946, "GUAYAQUIL": 242, "GUAYMAS": 215, "HALIFAX": 113, "HAMBURGO": 592, "HAMILTON": 126, "HANKO": 583, "HELSIMBORG": 634, "HELSINSKI": 581, "HONG KONG": 492, "HOUSTON": 159, "HUAHUM": 972, "HUASCO GUACOLDA": 920, "HUELVA": 565, "HUEMULES": 976, "IBANEZ PALAVICINI": 985, "ILO": 253, "IQUIQUE": 902, "IQUITOS": 254, "ISLA DE PASCUA": 929, "JACKSONVILLE": 143, "JUAN FERNANDEZ": 922, "KALMAR": 635, "KAOHSIUNG": 451, "KARHG ISLAND": 461, "KEELUNG": 452, "KEMI": 584, "KOBE": 443, "KOKKOLA": 585, "KOTKA": 586, "LA GUAIRA": 282, "LA PALLICE": 552, "LAGO VERDE": 973, "LE HAVRE": 553, "LEBU": 928, "LIORNA, LIVORNO": 543, "LIRQUEN": 909, "LISBOA": 611, "LIVERPOOL": 571, "LONDRES": 572, "LONG BEACH": 175, "LOS ANGELES": 174, "LOS LIBERTADORES": 965, "LOS VILOS": 199, "LOTA": 927, "MAHUIL MALAL": 966, "MALMO": 633, "MANILA": 431, "MANZANILLO": 217, "MAR DEL PLATA": 269, "MARACAIBO": 285, "MARSELLA": 554, "MAZATLAN": 216, "MEJILLONES": 915, "MENDOZA": 264, "MIAMI": 141, "MICHILLA": 206, "MILWAUKEE": 150, "MOBILE": 153, "MOJI": 447, "MONTE AYMOND": 981, "MONTEVIDEO": 272, "MONTREAL": 111, "MOSSEL-BAY": 716, "MUELLE HUACHIPATO": 818, "MUELLE INTERACID TRADING (CHILE) S.A.": 828, "NAGOYA": 445, "NAMPO": 421, "NAPOLES": 544, "NATALES": 936, "NECOCHEA": 263, "NEW HAVEN": 132, "NEW ORLEANS": 154, "NEW YORK": 134, "NORFOLK": 137, "NUREMBERG": 593, "OAKLAND": 160, "ODENSE": 645, "OLDENBURG": 599, "OLLAGUE": 961, "OOSTENDE": 605, "OSAKA": 442, "OSLO": 651, "OTROS PUERTOS ASIATICOS NO ESPECIFICADOS": 499, "OTROS PUERTOS CHILENOS": 997, "OTROS PUERTOS DE AFRICA NO ESPECIFICADOS": 799, "OTROS PUERTOS DE ALEMANIA NO ESPECIFICADOS": 596, "OTROS PUERTOS DE AMERICA NO ESPECIFICADOS": 399, "OTROS PUERTOS DE ARGENTINA NO ESPECIFICADOS": 261, "OTROS PUERTOS DE AUSTRALIA NO ESPECIFICADOS": 813, "OTROS PUERTOS DE BANGLADESH NO ESPECIFICADOS": 482, "OTROS PUERTOS DE BELGICA NO ESPECIFICADOS": 602, "OTROS PUERTOS DE BRASIL NO ESPECIFICADOS": 291, "OTROS PUERTOS DE BULGARIA NO ESPECIFICADOS": 522, "OTROS PUERTOS DE CANADA NO IDENTIFICADOS": 117, "OTROS PUERTOS DE CHINA NO ESPECIFICADOS": 413, "OTROS PUERTOS DE COLOMBIA NO ESPECIFICADOS": 231, "OTROS PUERTOS DE COREA DEL NORTE NO ESPECIFICADOS": 420, "OTROS PUERTOS DE COREA DEL SUR NO ESPECIFICADOS": 423, "OTROS PUERTOS DE CROACIA NO ESPECIFICADOS": 537, "OTROS PUERTOS DE DINAMARCA NO ESPECIFICADOS": 643, "OTROS PUERTOS DE ECUADOR NO ESPECIFICADOS": 241, "OTROS PUERTOS DE ESPANA NO ESPECIFICADOS": 561, "OTROS PUERTOS DE ESTADOS UNIDOS NO ESPECIFICADOS": 180, "OTROS PUERTOS DE EUROPA NO ESPECIFICADOS": 699, "OTROS PUERTOS DE FILIPINAS NO ESPECIFICADOS": 432, "OTROS PUERTOS DE FINLANDIA NO ESPECIFICADOS": 582, "OTROS PUERTOS DE FRANCIA NO ESPECIFICADOS": 551, "OTROS PUERTOS DE INDIA NO ESPECIFICADOS": 472, "OTROS PUERTOS DE INGLATERRA NO ESPECIFICADOS": 576, "OTROS PUERTOS DE IRAN NO ESPECIFICADOS": 462, "OTROS PUERTOS DE ITALIA NO ESPECIFICADOS": 541, "OTROS PUERTOS DE JAPON NO ESPECIFICADOS": 441, "OTROS PUERTOS DE LAS ANTILLAS HOLANDESAS NO ESPECIFICADOS": 301, "OTROS PUERTOS DE MEXICO NO ESPECIFICADOS": 210, "OTROS PUERTOS DE MONTENEGRO NO ESPECIFICADOS": 536, "OTROS PUERTOS DE NORUEGA NO ESPECIFICADOS": 652, "OTROS PUERTOS DE OCEANIA NO ESPECIFICADOS": 899, "OTROS PUERTOS DE PAISES BAJOS NO ESPECIFICADOS": 623, "OTROS PUERTOS DE PANAMA NO ESPECIFICADOS": 224, "OTROS PUERTOS DE PERU NO ESPECIFICADOS": 251, "OTROS PUERTOS DE PORTUGAL NO ESPECIFICADOS": 612, "OTROS PUERTOS DE RUMANIA NO ESPECIFICADOS": 512, "OTROS PUERTOS DE SERBIA NO ESPECIFICADOS": 534, "OTROS PUERTOS DE SINGAPUR NO ESPECIFICADOS": 491, "OTROS PUERTOS DE SUDAFRICA NO ESPECIFICADOS": 713, "OTROS PUERTOS DE SUECIA NO ESPECIFICADOS": 632, "OTROS PUERTOS DE TAIWAN NO ESPECIFICADOS": 453, "OTROS PUERTOS DE URUGUAY NO ESPECIFICADOS": 271, "OTROS PUERTOS DE VENEZUELA NO ESPECIFICADOS": 281, "OULO": 587, "PALENA CARRENLEUFU": 970, "PALM BEACH": 145, "PAMPA ALTA": 975, "PANGUIPULLI": 971, "PARANAGUA": 295, "PASO BUTA MALLIN": 824, "PASO GUANACO SONSO": 225, "PASO JAMA": 998, "PASO PEHUENCHE": 947, "PATACHE": 204, "PATILLOS": 913, "PENCO": 925, "PENSACOLA": 152, "PERCY": 939, "PEREZ ROSALES": 968, "PIETARSAARI": 588, "PINO HACHADO (LIUCURA)": 949, "PITTSBURGH": 148, "PLYMOUTH": 578, "PODGORITSA": 535, "PORI": 589, "PORT ARTHUR": 155, "PORT CARTIES": 120, "PORT-ELIZABETH": 715, "PORTLAND": 172, "POSEIDON": 208, "PRINCE RUPERT": 125, "PUERTO ANDINO": 938, "PUERTO ANGAMOS": 207, "PUERTO CABO FROWARD": 817, "PUERTO MADRYN": 268, "PUERTO MONTT": 910, "PUERTO WILLIAMS": 943, "PUERTOS DEL GOLFO DE MEXICO, OTROS NO ESPECIFICADOS COMPRENDIDOS ENTRE KEY WEST Y BROWNSVILLE": 122, "PUNTA ARENAS": 912, "PUNTA CHUNGO": 190, "QUEBEC": 124, "QUELLON": 933, "QUINTERO": 921, "RANCHO DE NAVES Y AERONAVES DE TRANSPORTE INTERNACIONAL": 900, "RIJEKA": 538, "RIO DE JANEIRO": 293, "RIO GRANDE DEL SUR": 294, "RIO MAYER": 954, "RIO MOSCO": 955, "ROCHESTER": 573, "ROSARIO": 270, "ROSTOCK": 598, "ROTTERDAM": 622, "RUAN": 558, "SAINT JOHN": 115, "SALDANHA": 714, "SALERNO": 545, "SALVADOR": 297, "SAN ANTONIO": 906, "SAN DIEGO": 176, "SAN FRANCISCO": 964, "SAN PEDRO DE ATACAMA": 962, "SAN SEBASTIAN": 982, "SAN VICENTE": 908, "SANTOS": 292, "SAO PAULO": 296, "SAVANAH": 140, "SAVONA": 547, "SEATTLE": 171, "SETUBAL": 613, "SEVILLA": 566, "SHANGAI": 411, "SHIMIZUI": 446, "SIDNEY": 811, "SOCOMPA": 963, "STAVANGER": 653, "STOCKTON": 161, "TALCAHUANO": 907, "TALTAL": 916, "TAMPA": 151, "TAMPICO": 211, "TARRAGONA": 567, "TERMINAL GRANELES DEL NORTE": 827, "TERMINAL MARITIMO ABASTIBLE": 829, "TERMINAL MARITIMO ENAEX": 822, "TERMINAL MARITIMO ENAP": 830, "TERMINAL MARITIMO ESCUADRON": 819, "TERMINAL MARITIMO OXIQUIM": 823, "TERMINAL MUELLE MECANIZADO ESPERANZA": 821, "TERMINAL PORTUARIO TERQUIM": 820, "TERRITORIO ANTARTICO CHILENO": 944, "TOCOPILLA": 914, "TOME": 924, "TORONTO": 116, "TORTEL": 935, "TRES PUENTES": 209, "TRIANA": 984, "VALENCIA": 569, "VALPARAISO": 905, "VANCOUVER": 114, "VARNA": 521, "VENTANAS": 948, "VERACRUZ": 213, "VILLA O'HIGGINS": 986, "VISVIRI": 956, "YAWATA": 448, "YOKOHAMA": 444, "ZEEBRUGGE": 603, "ZONA FRANCA IQUIQUE": 952, "ZONA FRANCA PUNTA ARENAS": 953}

VIAS_TRANSPORTE = {"AEREO": 4, "CARRETERO / TERRESTRE": 7, "COURIER/AEREO": 11, "FERROVIARIO": 6, "MARITIMA, FLUVIAL Y LACUSTRE": 1, "OLEODUCTOS, GASODUCTOS": 8, "OTRA": 10, "POSTAL": 5, "TENDIDO ELECTRICO (AEREO, SUBTERRANEO)": 9}

CLAUSULAS_VENTA = {"CFR": 2, "CIF": 1, "DDP": 9, "EXW": 3, "FAS": 4, "FCA": 7, "FOB": 5, "OTRA": 8, "S/CL": 6}

MODALIDAD_VENTA = {"A FIRME": 1, "BAJO COND.": 2, "BAJO CONDICION": 2, "COND-M.F.": 4, "CONS-LIBRE": 3, "EN CONSIGNACION CON UN MINIMO A FIRME": 4, "EN CONSIGNACION LIBRE": 3, "FIRME": 1, "SIN PAGO": 9}

TIPOS_BULTO = {"ARMAZON": 26, "ATADOS": 90, "ATAUD": 86, "AUTOMOTOR": 85, "BALA": 65, "BANDEJA": 27, "BARRAS": 16, "BARRIL": 44, "BARRILETE": 37, "BAUL": 24, "BIDON": 34, "BLOQUE": 19, "BOBINA": 91, "BOLSA": 64, "BOTELLA": 32, "BOTELLA DE GAS": 31, "CAJAS DE CARTON": 22, "CAJAS DE LATA": 29, "CAJAS DE MADERA": 28, "CAJAS NO ESPECIFICADAS": 40, "CAJON": 21, "CARRETE": 83, "CESTAS": 36, "CILINDRO": 12, "COFRE": 25, "CONTENEDOR DE 20 PIES DRY": 73, "CONTENEDOR DE 40 PIES DRY": 74, "CONTENEDOR NO ESPECIFICADO (OPEN TOP, TANK, FLAT RACK, OTROS)": 78, "CONTENEDOR REFRIGERADO 20 PIES": 75, "CONTENEDOR REFRIGERADO 40 PIES": 76, "CUBO": 51, "CUNETES": 46, "DAMAJUANA": 43, "ESTANQUE (NO UTILIZAR PARA CONTENEDOR TANK)": 77, "FARDO": 23, "FRASCO": 42, "GRANEL GASEOSO": 5, "GRANEL LIQUIDO": 4, "GRANEL SOLIDO, PARTICULAS FINAS (POLVO)": 1, "GRANEL SOLIDO, PARTICULAS GRANDES (NODULOS)": 3, "GRANEL SOLIDO, PARTICULAS GRANULARES (GRANOS)": 2, "JABAS": 35, "JARRO": 41, "JAULAS": 33, "LAMINAS": 82, "LINGOTES": 17, "MALETA": 63, "MAQUINARIA": 88, "NO EXISTE BULTO": 98, "OTROS BULTOS NO ESPECIFICADOS": 93, "PALLETS": 80, "PAQUETE": 61, "PIEZAS": 10, "PIPAS": 39, "PLANCHAS": 89, "RED": 66, "ROLLIZO": 20, "ROLLOS": 13, "SACOS": 62, "SIN EMBALAR": 99, "SOBRES": 67, "TABLERO": 81, "TAMBOR": 45, "TARROS": 47, "TONEL": 38, "TRONCOS": 18, "TUBOS": 11}

# Unidades de medida Aduana (tabla del DUS)
UNIDADES_MEDIDA = {
    "TMB": 1, "QMB": 2, "MKWH": 3, "TMN": 4, "KLT": 5, "KN": 6, "KB": 7, "QMN": 8,
    "MKN": 9, "U": 10, "DOC": 11, "U(JGO)": 12, "MU": 13, "MT": 14, "MT2": 15,
    "MCUB": 16, "PAR": 17, "KNFC": 18, "CARTON": 19, "KWH": 20, "GN": 21, "GB": 22,
    "BAR": 23, "LT": 24, "S.U.M.": 99,
}

# Formas de pago de exportación Aduana (FmaPagExp). Formato DTE: 21 = sin pago
# ("muestras sin carácter comercial"), y con 21 el MntTotal del DTE va en 0.
FORMAS_PAGO_EXP = {
    "COB1": 1, "COBRANZA": 1, "ACRED": 2, "ACREDITIVO": 2, "COB2": 11, "ACRED2": 12,
    "SIN PAGO": 21, "ANTICIPO": 32,
}

# Alias y acrónimos frecuentes en los sets del SII → nombre de la tabla de Aduana.
# Las claves se comparan con clave() (sin puntos ni acentos), así que "EE.UU.",
# "EE UU" y "EEUU" caen todos en la misma entrada.
_ALIAS_RAW = {
    # Vía de transporte / modalidad / bultos
    "AEREO": "AEREO", "MARITIMA, FLUVIAL Y LACUSTRE": "MARITIMA, FLUVIAL Y LACUSTRE",
    "CARRETERO": "CARRETERO / TERRESTRE", "TERRESTRE": "CARRETERO / TERRESTRE",
    "A FIRME": "A FIRME", "FIRME": "A FIRME",
    "EN CONSIGNACION CON UN MINIMO A FIRME": "EN CONSIGNACION CON UN MINIMO A FIRME",
    "CONTENEDOR REFRIGERADO": "CONTENEDOR REFRIGERADO 20 PIES",
    # Países: acrónimos y nombres cortos de uso corriente
    "USA": "ESTADOS UNIDOS DE AMERICA", "U.S.A.": "ESTADOS UNIDOS DE AMERICA",
    "US": "ESTADOS UNIDOS DE AMERICA", "EEUU": "ESTADOS UNIDOS DE AMERICA",
    "EE.UU.": "ESTADOS UNIDOS DE AMERICA", "EUA": "ESTADOS UNIDOS DE AMERICA",
    "ESTADOS UNIDOS": "ESTADOS UNIDOS DE AMERICA",
    "UNITED STATES": "ESTADOS UNIDOS DE AMERICA",
    "UK": "REINO UNIDO", "U.K.": "REINO UNIDO", "R. UNIDO": "REINO UNIDO",
    "GRAN BRETANA": "REINO UNIDO", "INGLATERRA": "REINO UNIDO",
    "REINO UNIDO DE GRAN BRETANA E IRLANDA DEL NORTE": "REINO UNIDO",
    "P. BAJOS": "PAISES BAJOS", "HOLANDA": "PAISES BAJOS", "NETHERLANDS": "PAISES BAJOS",
    "R.P. CHINA": "CHINA", "RP CHINA": "CHINA", "REPUBLICA POPULAR CHINA": "CHINA",
    "CHINA POPULAR": "CHINA", "R. CHECA": "REPUBLICA CHECA (D)",
    "REPUBLICA CHECA": "REPUBLICA CHECA (D)", "CHEQUIA": "REPUBLICA CHECA (D)",
    "RUSIA": "RUSIA (B)", "FEDERACION RUSA": "RUSIA (B)",
    "TAIWAN": "TAIWAN (FORMOSA)", "FORMOSA": "TAIWAN (FORMOSA)",
    "BIRMANIA": "MYANMAR (EX BIRMANIA)", "MYANMAR": "MYANMAR (EX BIRMANIA)",
    "EAU": "EMIRATOS ARABES UNIDOS", "E.A.U.": "EMIRATOS ARABES UNIDOS",
    "EMIRATOS ARABES": "EMIRATOS ARABES UNIDOS",
    "ALEMANIA FEDERAL": "ALEMANIA", "R.F. ALEMANA": "ALEMANIA",
    "COREA DEL SUR": "COREA DEL SUR", "COREA DEL NORTE": "COREA DEL NORTE",
    # Puertos escritos abreviados
    "S. ANTONIO": "SAN ANTONIO", "SN ANTONIO": "SAN ANTONIO", "VALPO": "VALPARAISO",
    "PTO MONTT": "PUERTO MONTT", "PTA ARENAS": "PUNTA ARENAS",
    "NUEVA YORK": "NEW YORK", "SHANGHAI": "SHANGAI",
}
_ALIAS = {clave(k): v for k, v in _ALIAS_RAW.items()}

# Índice tolerante por tabla: clave() → [(nombre oficial, código), ...]
_INDICES: dict = {}


def _indice(tabla: dict) -> dict:
    idx = _INDICES.get(id(tabla))
    if idx is None:
        idx = {}
        for nombre, cod in tabla.items():
            idx.setdefault(clave(nombre), []).append((nombre, cod))
        _INDICES[id(tabla)] = idx
    return idx


def _unico(cands: list, texto: str, que: str) -> int:
    if len({c for _, c in cands}) == 1:
        return cands[0][1]
    nombres = sorted({n for n, _ in cands})
    muestra = " o ".join(nombres[:4]) + (", ..." if len(nombres) > 4 else "")
    raise KeyError(f"{que} '{texto}' es ambiguo: puede ser {muestra}. Escribe el nombre exacto de la tabla de Aduana")


def _buscar(tabla: dict, texto: str, que: str) -> int:
    # 1. nombre exacto de la tabla
    if norm(texto) in tabla:
        return tabla[norm(texto)]
    # 2. acrónimo o alias conocido
    t = texto
    alias = _ALIAS.get(clave(texto))
    if alias:
        if norm(alias) in tabla:
            return tabla[norm(alias)]
        t = alias
    k = clave(t)
    if not k:
        raise KeyError(f"Falta {que}")
    idx = _indice(tabla)
    # 3. coincidencia tolerante (sin puntos, sin "(D)"/"(B)" de la tabla)
    if k in idx:
        return _unico(idx[k], texto, que)
    # 4. sigla escrita con puntos ("C.I.F." → "CIF")
    compacto = k.replace(" ", "")
    if compacto in tabla:
        return tabla[compacto]
    if compacto in idx:
        return _unico(idx[compacto], texto, que)
    # 5. prefijo por palabras completas ("CONTENEDOR REFRIGERADO" → "... 20 PIES")
    cands = [x for kk, v in idx.items()
             if kk.startswith(k + " ") or k.startswith(kk + " ") for x in v]
    if cands:
        return _unico(cands, texto, que)
    raise KeyError(f"{que} '{texto}' no está en la tabla de Aduana")


def cod_pais(t): return _buscar(PAISES, t, "País")
def cod_puerto(t): return _buscar(PUERTOS, t, "Puerto")
def cod_via(t): return _buscar(VIAS_TRANSPORTE, t, "Vía de transporte")
def cod_clausula(t): return _buscar(CLAUSULAS_VENTA, t, "Cláusula de venta")
def cod_modalidad(t): return _buscar(MODALIDAD_VENTA, t, "Modalidad de venta")
def cod_bulto(t): return _buscar(TIPOS_BULTO, t, "Tipo de bulto")
def cod_unidad(t): return _buscar(UNIDADES_MEDIDA, t, "Unidad de medida")
def cod_forma_pago(t): return _buscar(FORMAS_PAGO_EXP, t, "Forma de pago")
